# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: {{ k8s_master_hostname }}
  bindPort: {{ k8s_master_port }}
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
networking:
  serviceSubnet: {{k8s_svc_network}}
  podSubnet: {{ k8s_pod_network }}
  dnsDomain: {{k8s_dns_domain}}
kubernetesVersion: {{k8s_version}}
